sources:
- name: gnat
  feed: http://pipes.yahoo.com/pipes/pipe.run?_id=b5896405bdb116feac4ed791f41498ee&_render=rss&nocache=true
  name: Four Short Links
  homepage: http://radar.oreilly.com/nat/index.html
  influence: 30
- feed: http://waxy.org/links/index.xml
  name: Waxy
  homepage: http://waxy.org/
  influence: 20
- feed: http://mike.teczno.com/snippets/xml.php
  name: tecznotes
  homepage: http://mike.teczno.com/
  influence: 30
#- feed: http://feeds.feedburner.com/Tputh
#  name: TPUTH
#  homepage: http://www.tputh.com/
#  influence: 20
# pubDate is broken in TPUTH feed

aggregator:
  backtype_api_key: e2e2e2e2e2e2e2e2e2e2
  expire_after: 15 days
  