sources:
- name: Four Short Links (Nat Torkington)
  url: http://pipes.yahoo.com/pipes/pipe.run?_id=b5896405bdb116feac4ed791f41498ee&_render=json
  format: JSON
- name: Waxy Links (Andy Baio)
  url: http://waxy.org/links/index.xml
  format: RSS